# Generated by Django 5.0.6 on 2024-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('biologist', 'Biologist'), ('citizen', 'Citizen')], default='citizen', max_length=10),
        ),
    ]
