# Generated by Django 5.0.6 on 2024-06-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('biologist', 'Biologist'), ('citizen', 'Citizen')], default='citizen', max_length=10, null=True),
        ),
    ]
